### ISSUE TITLE
In Step-1 I got black screen

### ISSUE THREAD

**Issue by zengchuan** [vivek1794/webrtc-android-codelab#1]
The article is great but I got black sreen in Step-1. Why? I Use Nexus_6_API_25 emulator and compileSdkVersion 25,    buildToolsVersion "25.0.3"

**Comment by vivek1794** [comment]
Does your emulator has camera support? And did you enable camera permission from settings? The sample code doesn't handle the run-time permissions needed for Android M and above.

**Comment by lizarazu77** [comment]
i think @zengchuan need add runtime permission in your code

**Comment by emayoung** [comment]
Thanks @lizarazu77  I had the same issue, adding runtime permissions cleared it up.
