### ISSUE TITLE
How to run the server which source code in the directory named "signalling"?

### ISSUE THREAD

**Issue by freedomofme** [vivek1794/webrtc-android-codelab#22]
I tried use "python -m SimpleHTTPServer 8000", but seems not work.
"code 404, message File not found"
""GET /socket.io/?EIO=3&transport=polling HTTP/1.1" 404 -"

**Comment by bbonathan** [comment]
You can refer to https://codelabs.developers.google.com/codelabs/webrtc-web/#6

**Comment by connected-egallagher** [comment]
I was able to successfully run it using Node. 
Install Node, navigate to the Signalling folder in the terminal and use the command `node index.js`
For development purposes I made it an http request and removed the key and cert options from the request.

```
var os = require('os');
var nodeStatic = require('node-static');
var https = require('http');
var socketIO = require('socket.io');
var fs = require("fs");
var options = {
	// key: fs.readFileSync('key.pem'),
	// cert: fs.readFileSync('cert.pem')
};
```

**Comment by paveltech** [comment]
you need "key.pem" and "cert.pem" certificate.

**Comment by freedomofme** [comment]
Thank you for your help.
Sorry for late response.
