### ISSUE TITLE
Error while running the application

### ISSUE THREAD

**Issue by sachyn** [vivek1794/webrtc-android-codelab#4]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve project :libwebrtc.
     Required by:
         project :app
      > Project :app declares a dependency from configuration '_debugApkCopy' to configuration 'default' which is not declared in the descriptor for project :libwebrtc.
   > Could not find :libwebrtc:.
     Required by:
         project :app

**Comment by vivek1794** [comment]
You need to add the aar file as a module dependency to get the error go away :)

**Comment by vivek1794** [comment]
#3 duplicate issue
