### ISSUE TITLE
How to implement only Voice call

### ISSUE THREAD

**Issue by diaz9557** [vivek1794/webrtc-android-codelab#5]
First of all Thx for such great step wise sample.
 I need to implement only voice call . I have successfully runs the demo you provided .
But i am unable to implement only Voice calls. Do we need VideoRenderer and SurfaceViewRenderer to create voice only call ? Please provide a solution . I m currently following Step3  Thx 

` localPeer = peerConnectionFactory.createPeerConnection(rtcConfig, new CustomPeerConnectionObserver("localPeerCreation") {
            @Override
            public void onIceCandidate(IceCandidate iceCandidate) {
                super.onIceCandidate(iceCandidate);
                onIceCandidateReceived(iceCandidate);
            }

            @Override
            public void onAddStream(MediaStream mediaStream) {
                super.onAddStream(mediaStream);
                if(mediaStream.audioTracks.size() > 0) {
                    remoteAudioTrack = mediaStream.audioTracks.get(0);
                    remoteAudioTrack.setEnabled(true);
                }
            }
        });`

I am receiving the `remoteAudioTrack` but how to use it ?

**Comment by Vivektilva** [comment]
can i get solution for this: want to use webrtc only for voice call.

**Comment by diaz9557** [comment]
You do not need to handle Video stream in this case and WebRtc will take care of audio stream . So just remove all Video handling and it will work . Also watch out for Runtime permission.  

Make sure the PeerConnection has been made and ICECandidates are exchanged properly .
