### ISSUE TITLE
how to make it as http ?

### ISSUE THREAD

**Issue by sarathkumar654** [vivek1794/webrtc-android-codelab#9]
should I remove these one var https = require('https');

**Comment by vivek1794** [comment]
Yes. And instead add var http = require('http'); and make the necessary changes. 

Just a note: You need to have https for webrtc to work in browser. WebRTC getUserMedia js function would work on http only on localhost. Other domain/IP needs https.

**Comment by sarathkumar654** [comment]
can you provide package version and socket.io recent versions for package.json file
